apiVersion: apps/v1
kind: Deployment
metadata:
  name: kkuioyui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kkuioyui
  template:
    metadata:
      labels:
        app: kkuioyui
    spec:
      containers:
      - image: okteto.dev/kkuioyui:latest
        name: kkuioyui
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a26ef20d-40d9-48f2-8023-6fcd1912e61f"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "a26ef20d-40d9-48f2-8023-6fcd1912e61f"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
