apiVersion: v1
kind: Service
metadata:
  name: kkuioyui
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "kkuioyui"
    port: 8080
  selector:
    app: kkuioyui
